// <auto-generated />
using CarListApp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    [Migration("20260913165954_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("CarListApp.Api.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Toyota",
                            Model = "Camry",
                            Vin = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Honda",
                            Model = "Civic",
                            Vin = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Ford",
                            Model = "Mustang",
                            Vin = "5678901234"
                        },
                        new
                        {
                            Id = 4,
                            Make = "BMW",
                            Model = "3 Series",
                            Vin = "LLLFY2M0Y8XUC9WPW"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Nissan",
                            Model = "Altima",
                            Vin = "V61PMGG7AEJW9ZT8D"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Audi",
                            Model = "A4",
                            Vin = "4EE57GJKBAUTKG9LH"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Ford",
                            Model = "F-150",
                            Vin = "1FTFW1ED5MFA12345"
                        },
                        new
                        {
                            Id = 8,
                            Make = "Chevrolet",
                            Model = "Silverado",
                            Vin = "1GCEKEDC0LF543210"
                        },
                        new
                        {
                            Id = 9,
                            Make = "Hyundai",
                            Model = "Elantra",
                            Vin = "5NPDH4AE7LH987654"
                        },
                        new
                        {
                            Id = 10,
                            Make = "Jeep",
                            Model = "Wrangler",
                            Vin = "1C4HJXDG0LW135792"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
